title: Poor theme
description: Poor is a theme for Jekyll
theme_author: Momingcoder

author: Keming


paginate: 15
paginate_path: "/blog/page:num/"

permalink: /:title

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

markdown: kramdown
kramdown:
  input: GFM

mathjax:
  enable: true
  cdn: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.3/MathJax.js?config=TeX-MML-AM_CHTML

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
